# Generated by Django 4.2.11 on 2024-08-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='header',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
